require('general')
require('general_keymappings')
require('plugins')
require("treesitter_configuration")
require('plugin_setups')
require("lsp_configurations")
require("plugins_keymappings")
require("autoformat")
