vim.cmd('set mouse=a')
vim.cmd('set termguicolors')
vim.cmd('set number')
vim.cmd('set guifont=FiraCode\\ NF\\:h12')
vim.cmd('set hidden')
vim.cmd('set nobackup')
vim.cmd('set nowritebackup')
vim.cmd('set cmdheight=2')
vim.cmd('set updatetime=300')
vim.cmd('set signcolumn=number')
vim.cmd('autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o')
